### ISSUE TITLE
is this repo still active

### ISSUE THREAD

**Issue by japrozs** [sbmxc/hacktoberfest#349]
I'm going to be making some pull requests to this repo for `hacktober fest 2021`. Will you be accepting my pull requests. I plan on making all 5 pull requests to this repo.

**Comment by souvikpal2000** [comment]
Hey, assign me with the task of adding more programs to yours repositories like on Data Structures and Algorithms which will be helpful to all. Like programs on Linked List, Doubly Linked List, etc with all Operations(Insert, Delete, Delete from user defined Position).
You can view my repositories. Thank You.

**Comment by sbmxc** [comment]
Hi guys, I believe you only have to get your PR approved to qualify for the hacktoberfest. So, no need to keep this issue open. Create an MR and I will merge it.
