### ISSUE TITLE
ADD factorial and fibonacci code

### ISSUE THREAD

**Issue by SatishYadav00** [sbmxc/hacktoberfest#420]
you can add factorial and fibonacci code in your ripo.
assign me for this.

**Comment by Ruhika1417** [comment]
@sbmxc I can work on this issue relating to both of the problems, please assign me..

**Comment by sbmxc** [comment]
Hi guys, no need to assign an issue to someone specifically, you can just create a PR and I will approve it, given you are putting some quality code in the repo. Thanks!

**Comment by Ruhika1417** [comment]
@sbmxc is this issue already closed?

**Comment by sbmxc** [comment]
Yes @Ruhika1417 , as mentioned earlier you don't necessarily need to work on open issues for qualifying for hacktoberfest. An approved PR will work.
