### ISSUE TITLE
Bubble sort

### ISSUE THREAD

**Issue by Srujan-Rao** [sbmxc/hacktoberfest#565]
add bubble sort

**Comment by Amitpawar88** [comment]
Hello, this is my first PR please assign this to me

**Comment by Samar1110** [comment]
Hello, assign this issue to me

**Comment by avigarg820** [comment]
``from sys import stdin

def bubbleSort(arr, n) :
    for i in range(n-1):
        for j in range(n-i-1):
            if arr[j]> arr[j+1]:
                temp = arr[j]
                arr[j]= arr[j+1]
                arr[j+1] = temp
                
                

#Taking Input Using Fast I/O
def takeInput() :
    n = int(stdin.readline().strip())
    if n == 0 :
        return list(), 0

    arr = list(map(int, stdin.readline().strip().split(" ")))
    return arr, n


#to print the array/list
def printList(arr, n) : 
    for i in range(n) :
        print(arr[i], end = " ")
    print()


#main
t = int(stdin.readline().strip())

while t > 0 :
    
    arr, n = takeInput()
    bubbleSort(arr, n)
    printList(arr, n)

    t-= 1

**Comment by avigarg820** [comment]
I am submitting a code of bubble sort in python. I hope it is ok

**Comment by avigarg820** [comment]
> add bubble sort

I am submitting a code of bubble sort in python. I hope it is ok

**Comment by harshhes** [comment]
hey there can i add bubble sort in python solution?

**Comment by Yashmittal01** [comment]
please assign it to me
