### ISSUE TITLE
Creating and traversing a binary tree in Python

### ISSUE THREAD

**Issue by Fortune-Adekogbe** [sbmxc/hacktoberfest#585]
The goal here is to demonstrate how a binary tree can be created and the different ways to traverse it. Kindly assign this issue to me @sbmxc.

**Comment by harshiitsingh** [comment]
Hey @sbmxc, please assign me this issue.

**Comment by Kgaurav951** [comment]
hey @sbmxc,
Please assign this issue this issue to me
