### ISSUE TITLE
Sorting techniques in java

### ISSUE THREAD

**Issue by gandhi25samar** [sbmxc/hacktoberfest#598]
Hey I wan to add different sorting techniques in java , so please assign me this issue and add the hacktoberfest label to this.

**Comment by gandhi25samar** [comment]
Hey I have sent a PR. Please merge it and let me know

**Comment by Rohans-7** [comment]
Hey @sbmxc please assign this issue to me. It will be a really good first issue for someone like me who is just starting in the open source.
Thank you !!!

**Comment by SumedhDongre031** [comment]
can you assign me to contribute?

**Comment by Roshnijeewani3457** [comment]
Hi, Can you please assign this task to me to contribute.
