### ISSUE TITLE
Delete Node in BST

### ISSUE THREAD

**Issue by harshita9621** [sbmxc/hacktoberfest#605]
Can I work on this issue

**Comment by harshita9621** [comment]
@sbmxc can I work on this issue

**Comment by charu-chaturvedi** [comment]
@sbmxc I want to work on this issue please assign this to me. Thank you!

**Comment by akshaydubey05** [comment]
@sbmxc  i would like to contribute in this issue i am specialist in codeforces i can do this easily please assign this to me.
