### ISSUE TITLE
word game in python

### ISSUE THREAD

**Issue by ShubhamNagure** [sbmxc/hacktoberfest#702]
It is a simple guessing game..

Users can guess the words or letters out of a given list of unknown lists of '?'.
ex: `['?', '?', '?', '?', '?']`

Initially, the user will have 3 lives left. `Lives left: ❤❤❤` .

**Comment by Talardork** [comment]
hello i have already made this as a project in the past, please assign it to me for the hacktoberfest

**Comment by Vikas3100** [comment]
Hi @ShubhamNagure ,
I would like to contribute & I will take a look into this as my first step.
